# values for the addon
addons:
  aws_load_balancer_controller:
    enabled: true
  aws_ebs_csi_resources:
    enabled: true
  metrics_server:
    enabled: true
  karpenter:
    enabled: false
  kyverno:
    enabled: true
  nirmata_cluster_registrator:
    enabled: true
  external_secrets:
    enabled: true
  cni_metrics_helper:
    enabled: true
  cw_prometheus:
    enabled: false
  grafana_operator:
    enabled: false
  argocd:
    enabled: true # ArgoCD is enabled to replace the argocd installed at bootstrap time via terraform helm provider
  prometheus_node_exporter:
    enabled: true
  kube_state_metrics:
    enabled: true
  adot_collector:
    enabled: false
  opentelemetry_operator:
    enabled: false
  cert_manager:
    enabled: false
  eks_upgrade_insights_demo:
    enabled: false

