# values for the addon
addons:
  aws_load_balancer_controller:
    enabled: true
  aws_ebs_csi_resources:
    enabled: true
  metrics_server:
    enabled: true
  karpenter:
    enabled: false
  kyverno:
    enabled: true
  kyverno_policies:
    enabled: true
  nirmata_cluster_registrator:
    enabled: true
  kyverno_policy_reporter:
    enabled: false
  cni_metrics_helper:
    enabled: true
  cw_prometheus:
    enabled: false
  prometheus_node_exporter:
    enabled: true
  kube_state_metrics:
    enabled: true
  argocd:
    enabled: false # Disabled because is not deployed by the gitops-bridge helm chart and instead is deployed by the fleet-spoke-argocd ApplicationSet from the Hub Cluster https://github.com/aws-samples/fleet-management-on-amazon-eks-workshop/blob/riv24/gitops/fleet/bootstrap/control-plane/members-init/addons-argo-cd-appset.yaml
  external_secrets:
    enabled: false # Disabled because is not deployed by the gitops-bridge helm chart and instead is deployed by the fleet-spoke-external-secrets ApplicationSet the Hub Cluster https://github.com/aws-samples/fleet-management-on-amazon-eks-workshop/blob/riv24/gitops/fleet/bootstrap/control-plane/members-init/addons-aws-oss-external-secrets-appset.yaml
  adot_collector:
    enabled: false
  opentelemetry_operator:
    enabled: false
  cert_manager:
    enabled: false
